// App Reducer
export const SET_KEY_HOLDER = "SET_KEY_HOLDER"
export const SET_LOAD = "SET_LOAD"

// Complete Project Reducer
export const SET_COMPLETE_PROJECTS = "SET_COMPLETE_PROJECT"
export const ADD_COMPLETE_PROJECT = "ADD_COMPLETE_PROJECT"
export const CLEAR_COMPLETE_PROJECTS = "CLEAR_COMPLETE_PROJECTS"

// Project Reducer
export const SET_PROJECTS = "SET_PROJECTS"
export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT"
export const REMOVE_PROJECT = "REMOVE_PROJECT"
export const ADD_USER_TO_TEMP_PROJECT = "ADD_USER_PROJECT"
export const REMOVE_USER_FROM_TEMP_PROJECT = "REMOVE_USER_FROM_TEMP_PROJECT"

// User Reducer
export const SET_USERS = "SET_USERS"
export const UPDATE_USER = "UPDATE_USER" 
export const REMOVE_USER = "REMOVE_USER" 