// App Reducer
export const SET_KEY_HOLDER = "SET_KEY_HOLDER"

// Complete Project Reducer
export const SET_COMPLETE_PROJECTS = "SET_COMPLETE_PROJECT"
export const ADD_COMPLETE_PROJECT = "ADD_COMPLETE_PROJECT"
export const REMOVE_COMPLETE_PROJECT = "REMOVE_COMPLETE_PROJECT"

// Project Reducer
export const SET_PROJECTS = "SET_PROJECTS"
export const ADD_PROJECT = "ADD_PROJECT"
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const REMOVE_PROJECT = "REMOVE_PROJECT"

// Archive Reducer
export const SET_ARCHIVE = "SET_ARCHIVE"
export const ADD_TO_ARCHIVE = "ADD_TO_ARCHIVE"
export const REMOVE_FROM_ARCHIVE = "REMOVE_FROM_ARCHIVE"

// Active Project Reducer
export const SET_ACTIVE_PROJECTS = "SET_ACTIVE_PROJECTS"
export const ADD_ACTIVE_PROJECT = "ADD_ACTIVE_PROJECT"
export const UPDATE_ACTIVE_PROJECT = "UPDATE_ACTIVE_PROJECT"
export const REMOVE_ACTIVE_PROJECT = "REMOVE_ACTIVE_PROJECT"
export const ADD_USER_TO_TEMP_PROJECT = "ADD_USER_TO_TEMP_PROJECT"
export const REMOVE_USER_FROM_TEMP_PROJECT = "REMOVE_USER_FROM_TEMP_PROJECT"

// User Reducer
export const SET_USERS = "SET_USERS"
export const ADD_USER = "ADD_USER" 
export const UPDATE_USER = "UPDATE_USER" 
export const REMOVE_USER = "REMOVE_USER" 

// Document Reducer
export const SET_DOCUMENTS = "SET_DOCUMENTS"
export const ADD_DOCUMENT = "ADD_DOCUMENT"
export const REMOVE_DOCUMENT = "REMOVE_DOCUMENT"

// Invitation Reducer
export const SET_INVITATIONS = "SET_INVITATIONS"
export const ADD_INVITATION = "ADD_INVITATION"
export const REMOVE_INVITATION = "REMOVE_INVITATION"

// Load Reducer
export const LOAD_KEYHOLDER = "LOAD_KEYHOLDER"
export const LOAD_PROJECTS = "LOAD_PROJECTS"
export const LOAD_USERS = "LOAD_USERS"
export const LOAD_DOCUMENTS = "LOAD_DOCUMENTS"
export const LOAD_INVITATIONS = "LOAD_INVITATIONS"
export const LOAD_ARCHIVES = "LOAD_ARCHIVES"